baseURL = 'https://AaronLuo00.github.io/my-blog/'
# 默认语言设置
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "PaperMod"

# 启用机器人文件
enableRobotsTXT = true

# 构建设置
buildDrafts = false
buildFuture = false
buildExpired = false

# 启用表情符号
enableEmoji = true

# 分页设置
pagination = { pagerSize = 5 }

# 语言设置
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "My Blog"
    description = "My Personal Blog"
    [languages.en.params]
      author = "Your Name"
      
      # 主页信息（英文）
      [languages.en.params.homeInfoParams]
        Title = "Welcome to My Blog"
        Content = """
        This is my personal blog created with Hugo and PaperMod theme.

        - Here, I will share my thoughts, experiences, and knowledge
        - The theme uses PaperMod, a clean and modern Hugo theme
        """
      
      # 社交图标（英文）
      [[languages.en.params.socialIcons]]
        name = "github"
        url = "https://github.com/AaronLuo00"
      
      [[languages.en.params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/yourusername"
  
  [languages.zh-cn]
    languageName = "中文"
    weight = 2
    title = "我的博客"
    description = "我的个人博客"
    [languages.zh-cn.params]
      author = "您的名字"
      
      # 主页信息（中文）
      [languages.zh-cn.params.homeInfoParams]
        Title = "欢迎来到我的博客"
        Content = """
        这是我使用Hugo和PaperMod主题创建的个人博客。

        - 在这里，我将分享我的想法、经验和知识
        - 主题使用了PaperMod，一个简洁、现代的Hugo主题
        """
      
      # 社交图标（中文）
      [[languages.zh-cn.params.socialIcons]]
        name = "github"
        url = "https://github.com/AaronLuo00"
      
      [[languages.zh-cn.params.socialIcons]]
        name = "twitter"
        url = "https://twitter.com/yourusername"

# 菜单设置（英文）
[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/en/categories/"
    weight = 10
  
  [[languages.en.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/en/tags/"
    weight = 20

# 菜单设置（中文）
[languages.zh-cn.menu]
  [[languages.zh-cn.menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/zh-cn/categories/"
    weight = 10
  
  [[languages.zh-cn.menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/zh-cn/tags/"
    weight = 20

# 主要内容部分
[params]
  # 环境设置
  env = "production"
  
  # 主题设置
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # 禁用归档页面
  disableArchive = true

# Markdown渲染设置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
